Repository chibisafe/chibisafe, pull requests merged in 2023-06, with the labels that each got.

#390 [Feature] Bake settings into the html to prevent an API call
  .eslintrc.json
  packages/backend/src/main.ts
  packages/backend/src/routes/admin/service/SaveSettings.ts
  packages/frontend/components.d.ts
  packages/frontend/src/App.vue
  packages/frontend/src/assets/styles/index.css
  packages/frontend/src/components/header/Header.vue
  packages/frontend/src/components/masonry/Masonry.vue
  packages/frontend/src/components/upload/ChibiUploader.vue
  packages/frontend/src/main.ts
  packages/frontend/src/store/settings.ts
  packages/frontend/vite.config.ts
Labels: enhancement

#391 [Feature] Be able to middle click a file in the file viewer to open it in a new tab
  packages/frontend/components.d.ts
  packages/frontend/src/components/masonry/Masonry.vue
Labels: enhancement

#402 [Fix] Drag and drop not working (again)
  packages/frontend/src/components/upload/ChibiUploader.vue
Labels: bug

#403 [Feature] Migration script from chibisafe v4 to v5
  README.md
  package.json
  packages/migration/package.json
  packages/migration/src/index.ts
  yarn.lock
Labels: enhancement

#407 [Feature] Add missing API Key middlewares to user routes
  packages/backend/src/routes/album/CreateAlbum.ts
  packages/backend/src/routes/album/DeleteAlbum.ts
  packages/backend/src/routes/album/GetAlbum.ts
  packages/backend/src/routes/album/PurgeAlbum.ts
  packages/backend/src/routes/album/UpdateAlbum.ts
  packages/backend/src/routes/album/links/CreateAlbumLink.ts
  packages/backend/src/routes/album/links/DeleteAlbumLink.ts
  packages/backend/src/routes/album/links/EditAlbumLink.ts
  packages/backend/src/routes/album/links/GetAlbumLinks.ts
  packages/backend/src/routes/files/AddFileToAlbum.ts
  packages/backend/src/routes/files/AddTagToFile.ts
  packages/backend/src/routes/files/DeleteFile.ts
  packages/backend/src/routes/files/DeleteFileFromAlbum.ts
  packages/backend/src/routes/files/DeleteTagFromFile.ts
  packages/backend/src/routes/files/GetFile.ts
  packages/backend/src/routes/files/GetFiles.ts
  packages/backend/src/routes/tag/CreateTag.ts
  packages/backend/src/routes/tag/DeleteTag.ts
  packages/backend/src/routes/tag/GetTags.ts
  packages/backend/src/routes/user/Me.ts
Labels: enhancement

#408 [Feature] Add IP filtering and ban/unban
  packages/backend/src/routes/admin/ip/GetFilesFromIP.ts
  packages/frontend/src/components/modals/FileInformationModal.vue
  packages/frontend/src/components/modals/GenericConfirmationModal.vue
  packages/frontend/src/pages/dashboard/admin/ip/[ip].vue
  packages/frontend/src/store/files.ts
  packages/frontend/src/store/modals.ts
  packages/frontend/src/use/api.ts
Labels: enhancement, feature

#410 [feature] Add global rate-limit
  packages/backend/src/main.ts
  packages/backend/src/routes/auth/Login.ts
  packages/backend/src/routes/auth/Register.ts
  packages/backend/src/structures/interfaces.ts
  packages/backend/src/structures/routes.ts
  packages/backend/src/structures/settings.ts
  packages/frontend/components.d.ts
Labels: feature

#411 [Fixes] Design issues mostly
  packages/backend/src/routes/admin/users/GetUserWithFiles.ts
  packages/frontend/src/App.vue
  packages/frontend/src/components/breadcrumbs/Breadcrumbs.vue
  packages/frontend/src/components/header/Header.vue
  packages/frontend/src/components/modals/FileInformationModal.vue
  packages/frontend/src/components/pagination/Pagination.vue
  packages/frontend/src/components/sidebar/Sidebar.vue
  packages/frontend/src/components/upload/ChibiUploader.vue
  packages/frontend/src/components/wrappers/FilesWrapper.vue
  packages/frontend/src/pages/dashboard/admin/settings.vue
  packages/frontend/src/pages/index.vue
  packages/frontend/src/pages/login.vue
  packages/frontend/src/pages/register.vue
  packages/frontend/src/store/modals.ts
  packages/frontend/src/types.ts
  packages/frontend/tailwind.config.js
Labels: enhancement

#413 [Feature] Add command palette
  packages/backend/src/routes/files/Search.ts
  packages/frontend/components.d.ts
  packages/frontend/package.json
  packages/frontend/src/App.vue
  packages/frontend/src/components/modals/SearchModal.vue
  packages/frontend/src/components/pagination/Pagination.vue
  packages/frontend/src/pages/dashboard/uploads.vue
  packages/frontend/src/store/files.ts
  packages/frontend/src/store/modals.ts
  packages/frontend/src/use/api.ts
  packages/frontend/tailwind.config.js
  yarn.lock
Labels: enhancement, feature

#415 [Feature] Public and IP uploads management
  packages/backend/src/routes/admin/files/GetFiles.ts
  packages/backend/src/routes/admin/files/PurgePublic.ts
  packages/backend/src/routes/admin/ip/PurgeFiles.ts
  packages/backend/src/routes/admin/users/Purge.ts
  packages/backend/src/utils/File.ts
  packages/frontend/src/components/forms/InputWithOverlappingLabel.vue
  packages/frontend/src/components/modals/DeleteFileModal.vue
  packages/frontend/src/components/modals/GenericConfirmationModal.vue
  packages/frontend/src/components/modals/ManageUserModal.vue
  packages/frontend/src/pages/dashboard/admin/files.vue
  packages/frontend/src/pages/dashboard/admin/ip/[ip].vue
  packages/frontend/src/store/files.ts
  packages/frontend/src/use/api.ts
Labels: enhancement

#416 [Fix] Style for user settings
  packages/frontend/src/pages/dashboard/account.vue
Labels: enhancement

#417 [Fix] Keyboard shortcuts
  packages/frontend/package.json
  packages/frontend/src/App.vue
  yarn.lock
Labels: bug

#419 [Bugfix] Iterate through all the settings and normalize names
  packages/backend/src/main.ts
  packages/backend/src/routes/getSettings.ts
  packages/frontend/src/App.vue
  packages/frontend/src/components/header/Header.vue
  packages/frontend/src/components/sidebar/Sidebar.vue
  packages/frontend/src/components/upload/ChibiUploader.vue
  packages/frontend/src/store/settings.ts
Labels: bug

#421 [Fix] Wrong extension on production build
  packages/backend/src/structures/routes.ts
Labels: bug

#422 [Feature] Add documentation links
  packages/backend/src/main.ts
  packages/frontend/src/components/header/Header.vue
  packages/frontend/src/components/sidebar/Sidebar.vue
Labels: enhancement

#426 [Fix] Remove unused rules
  packages/backend/src/routes/GetSettings.schema.ts
  packages/backend/src/routes/album/GetAlbums.ts
  packages/backend/src/routes/files/Upload.ts
  packages/backend/src/utils/Docs.ts
Labels: bug

#428 [Feature] Better settings
  packages/backend/src/routes/admin/service/SaveSettings.schema.ts
  packages/backend/src/routes/admin/service/SaveSettings.ts
  packages/backend/src/routes/admin/service/Settings.schema.ts
  packages/backend/src/routes/admin/service/Settings.ts
  packages/backend/src/structures/settings.ts
  packages/frontend/src/components/forms/Input.vue
  packages/frontend/src/components/forms/InputWithOverlappingLabel.vue
  packages/frontend/src/pages/dashboard/account.vue
  packages/frontend/src/pages/dashboard/admin/settings.vue
  packages/frontend/tailwind.config.js
Labels: enhancement

#429 [Feature] Add custom domain and mixed case filenames
  packages/backend/src/main.ts
  packages/backend/src/prisma/migrations/20230629002506_add_path_and_mixed_case_settings/migration.sql
  packages/backend/src/prisma/schema.prisma
  packages/backend/src/routes/admin/files/GetFile.ts
  packages/backend/src/routes/admin/files/GetFiles.ts
  packages/backend/src/routes/admin/ip/GetFilesFromIP.ts
  packages/backend/src/routes/admin/users/GetUser.ts
  packages/backend/src/routes/admin/users/GetUserWithFiles.ts
  packages/backend/src/routes/album/GetAlbum.ts
  packages/backend/src/routes/album/GetAlbumWithIdentifier.ts
  packages/backend/src/routes/album/GetAlbums.ts
  packages/backend/src/routes/auth/Login.ts
  packages/backend/src/routes/auth/Register.ts
  packages/backend/src/routes/files/GetFile.ts
  packages/backend/src/routes/files/GetFiles.ts
  packages/backend/src/routes/files/Search.ts
  packages/backend/src/routes/files/Upload.ts
  packages/backend/src/structures/interfaces.ts
  packages/backend/src/structures/settings.ts
  packages/backend/src/utils/File.ts
  packages/frontend/src/App.vue
Labels: feature

#431 [Fixes] Pagination, Video preview, etc
  packages/backend/src/routes/album/GetAlbumWithIdentifier.schema.ts
  packages/backend/src/routes/album/GetAlbumWithIdentifier.ts
  packages/backend/src/routes/album/links/GetAlbumLinks.schema.ts
  packages/frontend/src/App.vue
  packages/frontend/src/components/masonry/Masonry.vue
  packages/frontend/src/components/modals/AlbumSettingsModal.vue
  packages/frontend/src/components/modals/ManageAlbumModal.vue
  packages/frontend/src/components/pagination/Pagination.vue
  packages/frontend/src/components/wrappers/FilesWrapper.vue
  packages/frontend/src/pages/a/[identifier].vue
  packages/frontend/src/use/api.ts
Labels: bug, enhancement

#432 [Design] Some updates
  packages/frontend/package.json
  packages/frontend/src/components/breadcrumbs/Breadcrumbs.vue
  packages/frontend/src/components/dropdown/AlbumDropdown.vue
  packages/frontend/src/components/header/Header.vue
  packages/frontend/src/components/masonry/Masonry.vue
  packages/frontend/src/components/masonry/MasonryPublic.vue
  packages/frontend/src/components/modals/AlbumSettingsModal.vue
  packages/frontend/src/components/modals/DeleteFileModal.vue
  packages/frontend/src/components/modals/GenericConfirmationModal.vue
  packages/frontend/src/components/modals/ManageAlbumModal.vue
  packages/frontend/src/components/modals/ManageUserModal.vue
  packages/frontend/src/components/modals/SearchModal.vue
  packages/frontend/src/components/pagination/Pagination.vue
  packages/frontend/src/components/sidebar/Sidebar.vue
  packages/frontend/src/components/table/FilesTable.vue
  packages/frontend/src/components/toast/Toast.vue
  packages/frontend/src/components/upload/ChibiUploader.vue
  packages/frontend/src/components/wrappers/FilesWrapper.vue
  packages/frontend/src/pages/dashboard/admin/statistics.vue
  packages/frontend/src/pages/dashboard/albums/index.vue
  packages/frontend/src/pages/index.vue
  packages/frontend/tsconfig.json
  packages/frontend/vite.config.ts
  yarn.lock
Labels: enhancement

#435 [Feature] Enable user quotas
  README.md
  packages/backend/src/prisma/migrations/20230629065805_add_user_quota/migration.sql
  packages/backend/src/prisma/schema.prisma
  packages/backend/src/routes/admin/service/SaveSettings.ts
  packages/backend/src/routes/admin/users/GetAllUsers.schema.ts
  packages/backend/src/routes/admin/users/GetAllUsers.ts
  packages/backend/src/routes/admin/users/SetQuota.schema.ts
  packages/backend/src/routes/admin/users/SetQuota.ts
  packages/backend/src/routes/files/Upload.ts
  packages/backend/src/routes/user/Me.schema.ts
  packages/backend/src/routes/user/Me.ts
  packages/backend/src/structures/interfaces.ts
  packages/backend/src/structures/schemas/StorageQuota.ts
  packages/backend/src/structures/settings.ts
  packages/backend/src/utils/User.ts
  packages/frontend/components.d.ts
  packages/frontend/src/App.vue
  packages/frontend/src/components/modals/GenericInputModal.vue
  packages/frontend/src/components/sidebar/Sidebar.vue
  packages/frontend/src/components/table/UsersTable.vue
  packages/frontend/src/pages/dashboard/account.vue
  packages/frontend/src/store/modals.ts
  packages/frontend/src/store/user.ts
  packages/frontend/src/types.ts
  packages/frontend/src/use/api.ts
Labels: feature

#440 [Fix] Remove dangling email property
  packages/frontend/src/pages/invite/[code].vue
  packages/frontend/src/pages/login.vue
  packages/frontend/src/pages/register.vue
Labels: bug

#439 [Feat] Move package version to main package.json
  package.json
  packages/backend/src/routes/GetVersion.ts
  packages/backend/src/utils/Docs.ts
  packages/backend/src/utils/Util.ts
  packages/frontend/vite.config.ts
Labels: enhancement
