Repository chibisafe/chibisafe, pull requests merged in 2023-09, with the labels that each got.

#462 [Feature] Snippets
  packages/backend/src/prisma/migrations/20230902195954_add_snippets/migration.sql
  packages/backend/src/prisma/schema.prisma
  packages/backend/src/routes/snippet/CreateSnippet.schema.ts
  packages/backend/src/routes/snippet/CreateSnippet.ts
  packages/backend/src/routes/snippet/DeleteSnippet.schema.ts
  packages/backend/src/routes/snippet/DeleteSnippet.ts
  packages/backend/src/routes/snippet/GetPublicSnippet.schema.ts
  packages/backend/src/routes/snippet/GetPublicSnippet.ts
  packages/backend/src/routes/snippet/GetSnippet.schema.ts
  packages/backend/src/routes/snippet/GetSnippet.ts
  packages/backend/src/routes/snippet/GetSnippetRaw.schema.ts
  packages/backend/src/routes/snippet/GetSnippetRaw.ts
  packages/backend/src/routes/snippet/GetSnippets.schema.ts
  packages/backend/src/routes/snippet/GetSnippets.ts
  packages/backend/src/utils/Snippet.ts
  packages/frontend/components.d.ts
  packages/frontend/package.json
  packages/frontend/src/components/highlight/Highlight.vue
  packages/frontend/src/components/modals/SearchModal.vue
  packages/frontend/src/components/modals/TextEditorModal.vue
  packages/frontend/src/components/sidebar/Sidebar.vue
  packages/frontend/src/components/upload/ChibiUploader.vue
  packages/frontend/src/pages/dashboard/admin/statistics.vue
  packages/frontend/src/pages/dashboard/snippets/[uuid].vue
  packages/frontend/src/pages/dashboard/snippets/index.vue
  packages/frontend/src/pages/s/[identifier].vue
  packages/frontend/src/store/modals.ts
  packages/frontend/src/types.ts
  packages/frontend/src/use/api.ts
  packages/frontend/src/use/highlight.ts
  packages/frontend/tailwind.config.js
  yarn.lock
Labels: feature

#463 [Feature] Show registration closed notice
  packages/frontend/src/pages/register.vue
Labels: enhancement

#464 [Feature] Use the new highlight component on the shared snippet page
  packages/frontend/package.json
  packages/frontend/src/pages/dashboard/snippets/[uuid].vue
  packages/frontend/src/pages/s/[identifier].vue
  yarn.lock
Labels: enhancement

#465 [Feature] Load .env for production, fixed
  packages/backend/package.json
  packages/backend/src/main.ts
  packages/backend/src/utils/Snippet.ts
  packages/frontend/src/components/highlight/Highlight.vue
Labels: enhancement

#466 [Fixed] snippets
  packages/backend/src/utils/Snippet.ts
  packages/frontend/src/components/modals/TextEditorModal.vue
  packages/frontend/src/pages/s/[identifier].vue
Labels: bug, enhancement

#468 [Feature] Log to console
  packages/backend/package.json
  packages/backend/src/main.ts
  packages/backend/src/middlewares/log.ts
  packages/backend/src/structures/routes.ts
  packages/backend/src/structures/settings.ts
  packages/backend/src/utils/File.ts
  packages/backend/src/utils/Logger.ts
  packages/backend/src/utils/Snippet.ts
  packages/backend/src/utils/StatsGenerator.ts
  packages/backend/src/utils/Thumbnails.ts
  packages/backend/src/utils/UpdateCheck.ts
  packages/backend/src/utils/Util.ts
  yarn.lock
Labels: enhancement

#471 [Fix] Hide admin section from non-admin users
  packages/frontend/src/components/sidebar/Sidebar.vue
Labels: bug

#474 [Feat] UI fixes
  package.json
  packages/backend/src/routes/admin/ip/GetBannedIPs.schema.ts
  packages/backend/src/routes/admin/ip/GetBannedIPs.ts
  packages/backend/src/routes/admin/ip/GetFilesFromIP.schema.ts
  packages/backend/src/routes/admin/ip/PurgeFiles.schema.ts
  packages/backend/src/structures/routes.ts
  packages/frontend/package.json
  packages/frontend/src/components/combobox/Combobox.vue
  packages/frontend/src/components/dialogs/AlbumSettingsDialog.vue
  packages/frontend/src/components/dialogs/ConfirmationDialog.vue
  packages/frontend/src/components/dialogs/FileInformationDialog.vue
  packages/frontend/src/components/dialogs/InputDialog.vue
  packages/frontend/src/components/masonry/NewMasonry.vue
  packages/frontend/src/components/modals/FileInformationModal.vue
  packages/frontend/src/components/sidebar/Sidebar.vue
  packages/frontend/src/components/table/AlbumLinksTable.vue
  packages/frontend/src/components/table/FilesTable.vue
  packages/frontend/src/components/table/InvitesTable.vue
  packages/frontend/src/components/table/UsersTable.vue
  packages/frontend/src/components/ui/alert-dialog/AlertDialogTrigger.vue
  packages/frontend/src/components/ui/button/index.ts
  packages/frontend/src/components/ui/dialog/DialogClose.vue
  packages/frontend/src/components/ui/dialog/DialogTrigger.vue
  packages/frontend/src/components/ui/dialog/index.ts
  packages/frontend/src/components/wrappers/FilesWrapper.vue
  packages/frontend/src/pages/dashboard/account.vue
  packages/frontend/src/pages/dashboard/admin/files/index.vue
  packages/frontend/src/pages/dashboard/admin/invites.vue
  packages/frontend/src/pages/dashboard/admin/ip/[ip].vue
  packages/frontend/src/pages/dashboard/admin/ip/index.vue
  packages/frontend/src/pages/dashboard/albums/index.vue
  packages/frontend/src/pages/dashboard/snippets/[uuid].vue
  packages/frontend/src/store/user.ts
  packages/frontend/src/use/api.ts
  yarn.lock
Labels: bug, enhancement, feature

#476 chore: upgrade @chibisafe/uploader version
  package.json
  packages/backend/package.json
  packages/frontend/package.json
  yarn.lock
Labels: dependencies

#490 [Fix] Enable scroll on album dropdown and snippet view
  packages/frontend/src/components/dropdown/AlbumDropdown.vue
  packages/frontend/src/pages/s/[identifier].vue
Labels: bug
