Repository chibisafe/chibisafe, pull requests merged in 2024-01, with the labels that each got.

#532 [Fix] Set quota dialog
  packages/frontend/src/components/dialogs/InputQuotaDialog.vue
  packages/frontend/src/components/table/UsersTable.vue
Labels: bug

#536 [Fix] Remove sharp
  packages/backend/package.json
  packages/backend/src/utils/Thumbnails.ts
  yarn.lock
Labels: bug

#539 [Feature] Add diagnostics button
  .gitignore
  .prettierignore
  package.json
  packages/backend/package.json
  packages/backend/src/main.ts
  packages/backend/src/routes/admin/service/Diagnostic.schema.ts
  packages/backend/src/routes/admin/service/Diagnostic.ts
  packages/frontend/src/pages/a/[identifier].vue
  packages/frontend/src/pages/dashboard/admin/settings.vue
  packages/frontend/src/use/api.ts
  yarn.lock
Labels: enhancement

#527 [fix] Fixed mobile scaling issues with FileInfoDialog
  packages/frontend/src/components/dialogs/FileInformationDialog.vue
Labels: bug

#534 [Feature] e2e tests with Playwright
  packages/frontend/.gitignore
  packages/frontend/package.json
  packages/frontend/playwright.config.ts
  packages/frontend/src/App.vue
  packages/frontend/src/components/dialogs/InputDialog.vue
  packages/frontend/src/router.ts
  packages/frontend/src/store/user.ts
  packages/frontend/tests/albums.spec.ts
  packages/frontend/tests/auth.setup.ts
  packages/frontend/tests/index.spec.ts
  yarn.lock
Labels: enhancement, tests

#540 [Feature] Add album descriptions
  packages/backend/src/prisma/migrations/20240115115628_add_description_to_albums_and_snippets/migration.sql
  packages/backend/src/prisma/schema.prisma
  packages/backend/src/routes/album/GetAlbum.schema.ts
  packages/backend/src/routes/album/GetAlbum.ts
  packages/backend/src/routes/album/GetAlbumWithIdentifier.schema.ts
  packages/backend/src/routes/album/GetAlbumWithIdentifier.ts
  packages/backend/src/routes/album/GetAlbums.schema.ts
  packages/backend/src/routes/album/GetAlbums.ts
  packages/backend/src/routes/album/UpdateAlbum.schema.ts
  packages/backend/src/routes/album/UpdateAlbum.ts
  packages/backend/src/routes/snippet/GetSnippet.schema.ts
  packages/backend/src/routes/snippet/GetSnippet.ts
  packages/frontend/src/components/dialogs/AlbumSettingsDialog.vue
  packages/frontend/src/components/dialogs/FileInformationDialog.vue
  packages/frontend/src/pages/a/[identifier].vue
  packages/frontend/src/store/albums.ts
  packages/frontend/src/types.ts
Labels: feature
